{
 "title": "AMD gpu custom",
 "time": { "from": "2025-09-09T16:18:48.562Z", "to": "2025-09-09T16:54:12.662Z" },
 "panels": [
  {
   "title": "Temperature",
   "type": "stat",
   "description": "Temp in Celcius",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "amd_gpu_temperature_celsius{gpu=\"0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fan speed",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "amd_gpu_fan_speed_percent{gpu=\"0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power Consumption",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "amd_gpu_power_watts{gpu=\"0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "amd_gpu_current_voltage{gpu=\"0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mclk / Sclk Clock",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rotmhz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "amd_gpu_current_mclk_clock{gpu=\"0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "amd_gpu_current_sclk_clock{gpu=\"0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "amd_gpu_usage_percent{gpu=\"0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Live Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "amd_gpu_temperature_celsius{gpu=\"0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Live power watt",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "amd_gpu_power_watts{gpu=\"0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Live Fan Speed",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "expr": "amd_gpu_fan_speed_percent{gpu=\"0\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}